### ISSUE TITLE
Can Not Calibrate next to 2 month in use ADC converter used 

### ISSUE THREAD

**Issue by Timjena** [GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK#4]
Can Not Calibrate Please Help it is in solution 12.88 for now and shows 9.5 and can not be calibrated 

last two month was all good and now I don't can recalibrate 

Enter EC Calibration Mode<<<
Please put the probe into the 1413us/cm or 2.76ms/cm or 12.88ms/cm buffer solution<<<
Only need two point for calibration one low (1413us/com) and one high(2.76ms/cm or 12.88ms/cm)<<<
voltage:1225.0000
temperature:23.0^C

rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091>>>Buffer Solution Error Try Again<<<
KValueTemp calculation formule: RES2 * ECREF * compECsolution / 1000.0 / voltage<<<
KValueTemp calculation: 820.00 * 200.00 * 1.36 / 1000.0 / 1225.00<<<
KValueTemp: 0.18<<<
KValueTemp out of range 0.5-2.0<<<
KValueTemp: 0.1822<<<
Failed,Try Again<<<
voltage:1225.0000
temperature:23.0^C

rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1225.0000
temperature:23.0^C
rawEC: 7.4695, ecValue: 9.5091<<<
xx:9.5091voltage:1227.0000

**Comment by Timjena** [comment]
>>>Enter EC Calibration Mode<<<
>>>Please put the probe into the 1413us/cm or 2.76ms/cm or 12.88ms/cm buffer solution<<<
>>>Only need two point for calibration one low (1413us/com) and one high(2.76ms/cm or 12.88ms/cm)<<<

voltage:976.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9512, ecValue: 8.2176<<<
xx:8.2176voltage:977.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9573, ecValue: 8.2260<<<
xx:8.2260voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513>>>Buffer Solution Error Try Again<<<   
>>>KValueTemp calculation formule: RES2 * ECREF * compECsolution / 1000.0 / voltage<<<
>>>KValueTemp calculation: 820.00 * 200.00 * 1.25 / 1000.0 / 980.00<<<

>>>KValueTemp: 0.21<<<

>>>KValueTemp out of range 0.5-2.0<<<
>>>KValueTemp: 0.2099<<<
>>>Failed,Try Again<<<

voltage:979.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9695, ecValue: 8.2428<<<
xx:8.2428voltage:977.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9573, ecValue: 8.2260<<<
xx:8.2260voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513voltage:979.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9695, ecValue: 8.2428<<<
xx:8.2428voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513voltage:980.0000
Requesting temperatures...temperature:19.0^C
>>>rawEC: 5.9756, ecValue: 8.2405<<<
xx:8.2405voltage:979.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9695, ecValue: 8.2428<<<
xx:8.2428voltage:980.0000
Requesting temperatures...temperature:19.0^C
>>>rawEC: 5.9756, ecValue: 8.2405<<<
xx:8.2405voltage:982.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9878, ecValue: 8.2681<<<
xx:8.2681voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513voltage:979.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9695, ecValue: 8.2428<<<
xx:8.2428voltage:979.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9695, ecValue: 8.2536<<<
xx:8.2536voltage:980.0000
Requesting temperatures...temperature:18.9^C
>>>rawEC: 5.9756, ecValue: 8.2513<<<
xx:8.2513voltage:980.0000
Requesting temperatures...temperature:18.9^C





it dose not work now with temp sensor for compensation but also nothing 1413 us/ml work good to Calibrate but 12.88 error try again

**Comment by MkLHX** [comment]
@Timjena 

-first point:
how many time the probe still in water?
RF robot probe cannot be used tu be continuously in water. 
"NOTE: Long-firing Operation: Sampling test method was used to test the EC value, dont support to immerse into solution for a long time, so please take out the electrode from solution after testing."
https://wiki.dfrobot.com/Analog_EC_Meter_SKU_DFR0300
-second point
as you can see the raw EC range for 12.88 solution is here:
https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK/blob/50644b96417f9a0f8f54b3621034e8400c65ca2d/src/DFRobot_ESP_EC.cpp#L264

and raw ec low and high are here:
https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK/blob/50644b96417f9a0f8f54b3621034e8400c65ca2d/src/DFRobot_ESP_EC.h#L31
https://github.com/GreenPonik/DFRobot_ESP_EC_BY_GREENPONIK/blob/50644b96417f9a0f8f54b3621034e8400c65ca2d/src/DFRobot_ESP_EC.h#L32

On your logs we can see raw EC is between 5.9 and 8.2 so the problem is not in code side but seems be a problem with your probe or your circuit. Your measurement circuit is hot? What is a reading cadence ?

-third point
Did you use both ec and ph probe on your setup? if you used both you have to put an isolator circuit on ph or ec measure circuit.

So check whole circuit and probe and if you have another test with it.

**Comment by joshcoward63** [comment]
Having this issue as well

**Comment by MkLHX** [comment]
Hi @joshcoward63 
Same answer like the last time. The current code is available for calibration with 1.413ms/cm and 2.76ms/cm solutions buffer.
So you can apply the modifications described on the last answer or use the correct buffers.

**Comment by Timjena** [comment]
Cleaning the titan plates helped me to calibrate the EC Sensor
